config/routes.rb
CruiseControl::Application.routes.draw do
  match '/(.:format)' => 'projects#index', :as => :root
  match 'projects/code/:id/*path' => 'projects#code', :as => :code
  match 'projects/kill_all_builders' => 'projects#kill_all_builders'

  resources :projects do
    member do
      post :build, :constraints => { :id => /.*/ }
      post :release_note, :constraints => { :id => /.*/ }
      post :kill_build, :constraints => { :id => /.*/ }
      get :getting_started, :constraints => { :id => /.*/ }
    end
  end

  match 'builds/:project/latest_successful(/*path)' => 'builds#latest_successful', :as => :latest_successful_build, :project => /[^\/]+/
  match 'builds/:project/:build/artifacts/*path' => 'builds#artifact', :as => :build_artifact, :build => /[^\/]+/, :project => /[^\/]+/
  match 'builds/:project/:build' => 'builds#show', :as => :build, :build => /[^\/]+/, :project => /[^\/]+/
  match 'builds/:project' => 'builds#show', :as => :project_without_builds, :project => /[^\/]+/

  match 'documentation/plugins' => 'documentation#plugins', :as => :plugin_doc_list
  match 'documentation/plugins/:type/:name' => 'documentation#plugins', :as => :plugin_doc, :name => /[^\/]+/

  match 'documentation/*path' => 'documentation#get', :as => :document
  match 'documentation' => 'documentation#get', :as => :document_root

  match 'XmlStatusReport.aspx' => 'projects#index', :format => 'cctray'
  match 'XmlServerReport.aspx' => 'projects#index', :format => 'cctray'

  # TODO Remove this.
  match '/:controller(/:action(/:id))'
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  caches_page :drop_down

  def show
    render :text => 'Project not specified', :status => 404 and return unless params[:project]
    @project = Project.find(params[:project])
    render :text => "Project #{params[:project].inspect} not found", :status => 404 and return unless @project

    if params[:build]
      @build = @project.find_build(params[:build])
      render :text => "Build #{params[:build].inspect} not found", :status => 404 and return if @build.nil?
    else
      @build = @project.last_build
      render :action => 'no_builds_yet' and return if @build.nil?
    end

    @builds_for_navigation_list, @builds_for_dropdown = partitioned_build_lists(@project)

    @autorefresh = @build.incomplete?

    brakeman_csv = File.join(@build.work_directory, 'tmp/brakeman.csv')
    @brakeman = BrakemanCharts.new(brakeman_csv)
  end

  def artifact
    render :text => 'Project not specified', :status => 404 and return unless params[:project]
    render :text => 'Build not specified', :status => 404 and return unless params[:build]
    render :text => 'Path not specified', :status => 404 and return unless params[:path]

    @project = Project.find(params[:project])
    render :text => "Project #{params[:project].inspect} not found", :status => 404 and return unless @project
    @build = @project.find_build(params[:build])
    render :text => "Build #{params[:build].inspect} not found", :status => 404 and return unless @build

    path = @build.artifact(params[:path] + (params[:format] ? ".#{params[:format]}" : '' ))
    if File.directory? path
      if File.exists?(File.join(path, 'index.html'))
        redirect_to request.fullpath + '/index.html'
      else
        render :template => 'builds/show_dir_index'
      end
    elsif File.exists? path
      disposition = params.has_key?("attachment") ? "attachment" : "inline"
      send_file(path, :type => get_mime_type(path), :disposition => disposition, :stream => false)
    else
      render_not_found
    end
  end

  def latest_successful
    render :text => 'Project not specified', :status => 404 and return unless params[:project]

    @project = Project.find(params[:project])
    render :text => "Project #{params[:project].inspect} not found", :status => 404 and return unless @project
    @build = @project.builds.find_all(&:successful?).last
    render :text => "No successful build found", :status => 404 and return unless @build

    redirect_to build_path(@project, @build) +
                (params[:path] ? "/#{params[:path]}" : "")
  end

  private

    MIME_TYPES = {
      "html" => "text/html",
      "js"   => "text/javascript",
      "css"  => "text/css",
      "gif"  => "image/gif",
      "jpg"  => "image/jpeg",
      "jpeg" => "image/jpeg",
      "png"  => "image/png",
      "zip"  => "application/zip"
    }

    def get_mime_type(name)
      Rack::Mime::MIME_TYPES[File.extname(name)] || "text/plain"
    end

    def partitioned_build_lists(project)
      builds = project.builds.reverse
      partition_point = CruiseControl::Configuration.build_history_limit

      return builds[0...partition_point], builds[partition_point..-1] || []
    end

end

app/helpers/builds_helper.rb
module BuildsHelper

  def file_mtime(path)
    file = @build.artifact(path)
    return if File.symlink?(file)

    mtime = File.mtime(file)
    if (mtime.to_i > Time.now.to_i - 24*60*60)
      mtime.strftime("%I:%M:%S %p")
    else
      mtime.strftime("%d-%m-%Y")
    end
  end

  def file_size(path)
    file = @build.artifact(path)
    File.size(file)
  end

  def file_type(path)
    file = @build.artifact(path)
    return 'directory' if File.directory?(file)
    Rack::Mime::MIME_TYPES[File.extname(file)] || 'unknown'
  end

  def select_builds(project, builds)
    return "" if builds.blank?

    options = [ [ "Older Builds...", nil ] ] + builds.map do |build|
      [ build_to_text(build, false), build_path(project.id, build.label) ]
    end

    select_tag "build", options_for_select(options)
  end

  def format_build_log(log)
    highlight_test_count(link_to_code(convert_ansi_colors(log.html_safe)))
  end
  
  def link_to_changeset
    if review_changeset_url = CruiseControl::Configuration.review_changeset_url
      content_tag('p') do
        button_tag('Review changeset', :href => review_changeset_url.sub('%{changeset}', @build.revision.to_s))
      end
    end
  end

  def link_to_code(log)
    return log if CruiseControl::Configuration.disable_code_browsing
    @work_path ||= File.expand_path(@project.path + '/work')

    # https://github.com/rails/rails/issues/1555
    # Rails mucks with gsub with SafeBuffer...so turn it into a normal string first
    # not sure if this is a security issue or not...
    log.to_str.gsub(/(\#\{RAILS_ROOT\}\/)?([\w\.-]*\/[ \w\/\.-]+)\:(\d+)/) do |match|
      path = File.expand_path($2, @work_path)
      line = $3
      if path.index(@work_path) == 0
        path = path[@work_path.size..-1]
        link_to(match, "/projects/code/#{@project.name.html_safe}#{path}?line=#{line}##{line}")
      else
        match
      end
    end
  end

  def format_project_settings(settings)
    settings = settings.strip
    if settings.empty?
      "This project has no custom configuration. Maybe it doesn't need it."
    else
      settings.html_safe
    end
  end

  def format_build_script(script)
    if script.blank?
      "This project has no `build.sh` or `script/build` scripts. Maybe it doesn't need it."
    else
      script.html_safe
    end
  end

  def failures_and_errors_if_any(log)
    BuildLogParser.new(log).failures_and_errors
  end

  def format_test_error_output(test_error)
    message = test_error.message

    "Name: #{test_error.test_name}\n" +
    "Type: #{test_error.type}\n" +
    "Message: #{h message}\n\n" +
    "<span class=\"error\">#{h test_error.stacktrace}</span>\n\n\n"
  end

  def display_build_time
    build_time_text = remove_leading_zero I18n.l(@build.time, :format => :verbose)

    if @build.incomplete?
      if @build.latest?
        "building for #{format_seconds(@build.elapsed_time_in_progress, :general)}"
      else
        "started at #{build_time_text}, and never finished"
      end
    else
      elapsed_time_text = elapsed_time(@build, :precise)
      result_text = elapsed_time_text.empty? ? "finished at #{build_time_text}" : "finished at #{build_time_text} taking #{elapsed_time_text}"
      result_text << ", covered #{format_percent(@build.coverage)}%" if @build.coverage
      result_text.html_safe
    end
  end
  
  def coverage_icon(build)
    coverage = build.coverage
    coverage_text = coverage ? format_percent(coverage) : ''
    content_tag('div', coverage_text, :class => "coverage_icon coverage_#{coverage_status(coverage)}")
  end
  
  def coverage_status_icon(build)
    if coverage = build.coverage
      image_tag("coverage_#{coverage_status(coverage)}.png", :class => 'coverage_icon')
    else
      image_tag('coverage_none.png', :class => 'coverage_icon')
    end
  end

  private

  def highlight_test_count(log)
    log.gsub(/\d+ tests, \d+ assertions, \d+ failures, \d+ errors/, '<div class="test-results">\0</div>').
        gsub(/\d+ examples, \d+ failures/, '<div class="test-results">\0</div>')
  end

  def strip_ansi_colors(log)
    log.gsub(/\e\[\d+m/, '')
  end
  
  def convert_ansi_colors(log)
    AnsiColors.ansi_escaped(log).html_safe
  end
  
end

app/views/builds/_build_buttons.html.erb
<div class="buttons">
  <% if project.building? %>
    <%= image_tag 'spinner.gif', :class => "spinner" %>
  <% end %>

  <button id="release_note" >Release Note</button>

  <%= render :partial => "builds/release_note_form", :locals => { :project => project } %>

  <%= form_tag(build_project_path(:id => project), :class => "build_project") do %>

    <% if project.builder_down? %>
      <button type="submit" name="build_now" class="build_button">Start Builder</button>
    <% elsif project.can_build_now? %>
      <button type="submit" name="build_now" class="build_button">Build Now</button>
    <% else %>
      <button type="submit" name="build_now" class="build_button" disabled="disabled">Build Now</button>
    <% end %>

  <% end %>

  <% unless project.builder_down? %>
    <%= form_tag(kill_build_project_path(:id => project), :class => "build_project") do %>
      <% if project.can_kill_builder? %>
        <button type="submit" name="build_now" class="kill_build_button">Kill Builder</button>
      <% else %>
        <button type="submit" name="build_now" class="kill_build_button" disabled="disabled">Kill Builder</button>
      <% end %>
    <% end %>
  <% end %>
</div>
<script>
  $('#release_note_popup').dialog({ autoOpen: false , width : 'auto' });

  $("#release_note").live("click", function(e) {
    $('#release_note_popup').dialog('open');
  });


</script>

app/views/builds/_release_note_form.html.erb
<div id="release_note_popup" style="display:none" >
  <%= form_tag(release_note_project_path(:id => project), :id => "release_note_form" , :class => "build_project" ) do %>

      <dl>
         
          <dt><label for="from">From Revision No</label></dt>
          <dd><input type="text" id="from" name="from"></input></dd>

          <dt><label for="to">To Revision No</label></dt>
          <dd><input type="text" id="to" name="to" ></input></dd>

          <dt><label for="email">Send Release Note To Email</label></dt>
          <dd><input type="text" id="email" name="email" ></input></dd>

          <dt><label for="release_label"></label>Release Label (optional)</dt>
          <dd><input type="text" id="release_label" name="release_label" ></input></dd>

          <dt><label for="message">Message</label></dt>
          <dd><textarea cols="80" rows="7" id="message" name="message"></textarea></dd>
      </dl>



      <button type="submit" id="generate_release_note" name="generate_release_note" class="build_button">Generate</button>

  <% end %>
</div>

app/views/builds/no_builds_yet.html.erb
<div id="no_builds_help" class="help">
  <p><%= h @project.name %> doesn't have any builds yet.</p>
  <p>
    To start building this project, you need to start the builder. Open command line in the directory where you
    unpacked CruiseControl.rb, and type:
  </p>
  <pre style="font-family: courier, monospace">  cruise build <%= h @project.name %></pre>
</div>

app/views/builds/show.html.erb
<% @rss_feeds = {"#{@project.name} builds" => {:controller => 'projects', :action => 'show', :id => @project, :format => 'rss'}} -%>

<div id="build">
  <div class="left_column">
    <ul class="builds_list">
      <li class="build_link builder_control">
        <%= render :partial => 'builds/build_buttons', :locals => { :project => @project } %>
      </li>
      <% @builds_for_navigation_list.each do |build| %>
        <li class="build_link<%= ' selected' if @build.label == build.label %>">
          <%= coverage_icon(build) %>
          <%= link_to_build(@project, build) %>
        </li>
      <% end %>

      <% unless @builds_for_dropdown.empty? %>
        <li class="build_link old_build_selector">
          <label for="select_build">Older:</label>
          <select id="select_build">
            <%= content_tag :option, "Older Builds...", :value => "" %>
            <% @builds_for_dropdown.each do |build| %>
              <%= content_tag :option, build_label(build), :value => build_path(:project => @project.name, :build => build.label) %>
            <% end %>
          </select>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="main_content">
    <div class="build_header">
      <h1>
        <%= h @project.name %> build <%= h @build.abbreviated_label %>
      </h1>

      <div id="project_build_now" class="builder_control">
        <%= render :partial => "builds/build_buttons", :locals => { :project => @project } %>
      </div>

      <div class="build_time">
        <%= display_build_time %>
      </div>
    </div>

    <div class="build_details">
      <% test_failures   = failures_and_errors_if_any(@build.output) %>
      <% plugin_errors   = @build.plugin_errors %>
      <% build_artifacts = @build.additional_artifacts %>

      <ul class="build_nav">
        <li class="section_name active"><a href="#build_log">Build Log</a></li>
        <li class="section_name"><a href="#build_changeset">Build Changeset</a></li>

        <% if test_failures.any? %>
          <li class="section_name"><a href="#test_failures">Test Failures/Errors</a></li>
        <% end %>

        <% if plugin_errors.present? %>
          <li class="section_name"><a href="#plugin_errors">Plugin Errors</a></li>
        <% end %>

        <% if build_artifacts.any? %>
          <li class="section_name"><a href="#build_artifacts">Build Artifacts</a></li>
        <% end %>

        <li class="section_name">
          <a href="#project_settings">Project Settings</a>
        </li>

        <li class="section_name">
          <a href="#build_script">Build Script</a>
        </li>

        <li class="section_name">
          <a href="#brakeman_report">Security Report</a>
        </li>

        <% coverage_report = File.join(@build.artifacts_directory, 'coverage/index.html') -%>
        <% if File.exist?(coverage_report) -%>
          <li class="section_link">
            <%= link_to 'Coverage Report', build_artifact_path(:project => @project.name, :build => @build.label, :path => 'coverage/index.html') %>
          </li>
        <% end -%>
      </ul>

      <div class="sections">
        <div class="section active" id="build_log">
          <a name="build_log"></a>
          <% if @build.output_exceeds_max_file_display_length? %>
            <p>
              The size of the file you're viewing now is <%= number_to_human_size(@build.build_log.size) %>, which is too big to display in the dashboard;
              CC.rb is configured to truncate any files longer than <%= number_to_human_size(CruiseControl::Configuration.max_file_display_length) %>.
              You can override this value in <code>site_config.rb</code> by setting <code>max_file_display_length</code>
              to your desired value in bytes (e.g. <code>50.kilobytes</code>), or <code>nil</code> to allow files of any length.
            </p>

            <p>File path: <code><%= @build.build_log.expand_path %></code><br/></p>
          <% end %>

          <p>
            <%= button_tag "Download full log", :href => build_artifact_path(:project => @project.name, :build => @build.label, :path => 'build.log', :attachment => 1) %>
            or
            <%= link_to "View full log", build_artifact_path(:project => @project.name, :build => @build.label, :path => 'build.log') %>
          </p>

          <div class="section_content terminal_output"><%= format_build_log(@build.output).html_safe %></div>
        </div>

        <div class="section" id="build_changeset">
          <a name="build_changeset"></a>
          <%= link_to_changeset %>
          <div class="section_content terminal_output"><%= format_changeset_log(@build.changeset) %></div>
        </div>

        <% if test_failures.any? %>
          <div class="section" id="test_failures">
            <a name="test_failures"></a>
            <div class="section_content">
              <ul>
                <% test_failures.each do |failure| %>
                  <li class="test_failure <%= failure.type.underscore %>">
                    <div class="test_name"><%= failure.test_name %></div>
                    <div class="stacktrace"><%= link_to_code(failure.stacktrace).html_safe %></div>
                    <div class="message terminal_output"><%= failure.message %></div>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <% if plugin_errors.present? %>
          <div class="section" id="plugin_errors">
            <a name="plugin_errors"></a>
            <div class="section_content terminal_output"><%= h plugin_errors %></div>
          </div>
        <% end %>

        <% unless @build.additional_artifacts.empty? %>
          <div class="section" id="build_artifacts">
            <a name="build_artifacts"></a>
            <div class="section_content">
              <% @build.additional_artifacts.each do |artifact| %>
                <div class="artifact">
                  <%= link_to artifact, build_artifact_path(:project => @project.name, :build => @build.label, :path => artifact) %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="section" id="project_settings">
          <a name="project_settings"></a>
          <div class="section_content terminal_output"><%= format_project_settings(@build.project_settings) %></div>
        </div>

        <div class="section" id="build_script">
          <a name="build_script"></a>
          <div class="section_content terminal_output"><%= format_build_script(@build.build_script) %></div>
        </div>

        <div class="section" id="brakeman_report">
          <a name="brakeman_report"></a>
          <div class="section_content">
            <% if @brakeman.valid? -%>
              <p><%= image_tag @brakeman.warning_chart -%></p>
              <p><%= image_tag @brakeman.scanned_chart -%></p>
            <% else %>
              <div class="section_content terminal_output">Please execute: bundle exec brakeman --quiet --summary --output tmp/brakeman.csv;</div>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/builds/show_dir_index.html.erb
<h3>Listing <%= params[:path] %> </h3>
<table>
  <tr>
    <th>File</th>
    <th>Last Modified</th>
    <th>Size</th>
    <th>Type</th>
  </tr>
  <% @build.files_in(params[:path]).each do |f| %>
  <tr>
    <td><%= link_to f, f %></td>
    <td><%= file_mtime(f) %></td>
    <td><%= file_size(f) rescue 0 %> bytes</td>
    <td><%= file_type(f) %></td>
  </tr>
  <% end %>
</table>