config/routes.rb
CruiseControl::Application.routes.draw do
  match '/(.:format)' => 'projects#index', :as => :root
  match 'projects/code/:id/*path' => 'projects#code', :as => :code
  match 'projects/kill_all_builders' => 'projects#kill_all_builders'

  resources :projects do
    member do
      post :build, :constraints => { :id => /.*/ }
      post :release_note, :constraints => { :id => /.*/ }
      post :kill_build, :constraints => { :id => /.*/ }
      get :getting_started, :constraints => { :id => /.*/ }
    end
  end

  match 'builds/:project/latest_successful(/*path)' => 'builds#latest_successful', :as => :latest_successful_build, :project => /[^\/]+/
  match 'builds/:project/:build/artifacts/*path' => 'builds#artifact', :as => :build_artifact, :build => /[^\/]+/, :project => /[^\/]+/
  match 'builds/:project/:build' => 'builds#show', :as => :build, :build => /[^\/]+/, :project => /[^\/]+/
  match 'builds/:project' => 'builds#show', :as => :project_without_builds, :project => /[^\/]+/

  match 'documentation/plugins' => 'documentation#plugins', :as => :plugin_doc_list
  match 'documentation/plugins/:type/:name' => 'documentation#plugins', :as => :plugin_doc, :name => /[^\/]+/

  match 'documentation/*path' => 'documentation#get', :as => :document
  match 'documentation' => 'documentation#get', :as => :document_root

  match 'XmlStatusReport.aspx' => 'projects#index', :format => 'cctray'
  match 'XmlServerReport.aspx' => 'projects#index', :format => 'cctray'

  # TODO Remove this.
  match '/:controller(/:action(/:id))'
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ActionView::Helpers::TextHelper

  before_filter :disable_build_triggers, :only => [:build, :kill_build]
  before_filter :disable_add_project, :only => :create
  
  def index
    @projects = Project.all

    respond_to do |format|
      format.html do
        if request.xhr?
          render_projects_partial(@projects)
        else
          render 'index'
        end
      end
      format.rss { render :action => 'index_rss', :layout => false, :format => :xml }
      format.cctray { render :action => 'index_cctray', :layout => false, :format => :xml }
      format.json { render :json => @projects.map { |p| project_to_attributes(p) } }
    end
  end

  def create
    scm = SourceControl.create(params[:project][:source_control])
    project = Project.create(params[:project][:name], scm)
    redirect_to getting_started_project_path(project.id)
  rescue ArgumentError => e
    redirect_to new_project_path, :flash => {:notice => e.message}
  end

  def getting_started
    @project = Project.find(params[:id])
    @config_example = File.read( Rails.root.join("config", "cruise_config.rb.example") )
  end

  def show
    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project

    respond_to do |format|
      format.html { redirect_to :controller => "builds", :action => "show", :project => @project }
      format.rss { render :action => 'show_rss', :layout => false }
      format.json { render :json => project_to_attributes(@project) }
    end
  end

  def build
    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project

    @project.request_build rescue nil

    respond_to do |format|
      format.html do
        if request.xhr?
          render_projects_partial(Project.all)
        else
          redirect_to :controller => "builds", :action => "show", :project => @project
        end
      end
    end
  end

  def release_note
    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project

    @project.generate_release_note(params[:from], params[:to], params[:message], params[:email], params[:release_label] ) rescue nil

    respond_to do |format| 
      format.html do
        if request.xhr?
          render_projects_partial(Project.all)
        else
          redirect_to :controller => "builds", :action => "show", :project => @project
        end
      end
    end
  end

  def kill_build
    @project = Project.find(params[:id])
    @project.kill_build rescue nil

    respond_to do |format|
      format.html do
        if request.xhr?
          render_projects_partial(Project.all)
        else
          redirect_to :action => 'index'
        end
      end
    end
  end

  def kill_all_builders
    killed = []

    @projects = Project.all
    @projects.each do |project|
      unless project.builder_down?
        project.kill_build rescue nil
        killed << project.name
      end
    end
    flash[:notice] = "#{pluralize(killed.count, 'project')} killed: #{killed.join(", ")}"

    respond_to do |format|
      format.html do
        if request.xhr?
          render_projects_partial(Project.all)
        else
          redirect_to :action => 'index'
        end
      end
    end
  end

  def code
    if CruiseControl::Configuration.disable_code_browsing
      render :text => "Code browsing disabled" and return
    end

    @project = Project.find(params[:id])
    render :text => "Project #{params[:id].inspect} not found", :status => 404 and return unless @project

    path = File.join(@project.path, 'work', params[:path])
    @line = params[:line].to_i if params[:line]

    if File.directory?(path)
      render :text => 'Viewing of source directories is not supported yet', :status => 500
    elsif File.file?(path)
      @content = File.read(path)
    else
      render_not_found
    end
  end


  private

    def render_projects_partial(projects)
      if projects.empty?
        render :partial => 'no_projects'
      else
        render :partial => 'project', :collection => projects
      end
    end

    def project_to_attributes(project)
      { 'name' => project.name }
    end
    
    def disable_add_project
      return unless CruiseControl::Configuration.disable_add_project
      render :text => 'Build requests are not allowed', :status => :forbidden
    end
end

app/helpers/projects_helper.rb
require 'digest/md5'

module ProjectsHelper

  def last_commit_avatar project
    email = project.source_control.latest_commiter_email
    hash = Digest::MD5.hexdigest(email)
    image_tag "http://www.gravatar.com/avatar/#{hash}", { :alt => email }
  end

  def rss_title(project, build)
    project.name + (build ? " build #{build.abbreviated_label} #{build.status}" :
                            " has never been built")
  end

  def rss_description(project, build)
    build ? build.changeset : ''
  end

  def rss_pub_date(build)
    time = (build.try(:time) || Time.at(0)).utc
    I18n.l time, :format => :rss
  end

  def rss_link(project, build)
    build ? build_url(:only_path => false, :project => project, :build => build) :
            project_without_builds_url(:only_path => false, :project => project)
  end

  def show_revisions_in_build(revisions)
    return '' if revisions.empty?
    if revisions.length == 1
      revision = revisions[0]
      text = "<div><span class='build_author'>#{revision.author}</span>" + ' committed the checkin</div>'
      # TODO: <br/> - should probably use css instead.
      text += '<br/>'
      text +="<div>Comments:<br/>#{format_changeset_log(revision.message)}</div>" unless revision.message.empty?
      text
    else
      committers = revisions.collect { |rev| rev.author }.uniq
      text = "<div><span class='build_author'>#{committers.join(', ')}</span>" + ' committed the checkin</div>'
    end
  end

  def revisions_in_build(build)
    changeset = build.changeset
    SourceControl::Subversion::ChangesetLogParser.new.parse_log changeset.split("\n")
  end

  # Re-map our project statuses to match the project statuses recognized
  # by CCTray.Net
  def map_to_cctray_project_status(project_status)
    case project_status.to_s
    when 'success', 'building' then 'Success'
    when 'never_built' then 'Unknown'
    when 'failed' then 'Failure'
    else 'Unknown'
    end
  end

  # Re-map our build activities to match the build activities recognized
  # by CCTray.Net
  def map_to_cctray_activity(builder_state)
    case builder_state.to_s
    when 'checking_for_modifications' then 'CheckingModifications'
    when 'building' then 'Building'
    when 'sleeping', 'builder_down' then 'Sleeping'
    else 'Unknown'
    end
  end
  
  def coverage_delta(project)
    '%+0.1f' % project.last_coverage_delta
  end
  
  def coverage_status(coverage)
    Coverage.status(coverage).to_s
  end
end

app/views/projects/_no_projects.html.erb
<div id="no_projects_help" class="help">
  <h1>Welcome to CruiseControl.rb!</h1>
  <div style="padding: 1em;">
    <p>
      No projects are currently configured (checked <small><%= h CruiseControl::Configuration.projects_root %></small>).
    </p>
    <h3>Adding a new project</h3>
    <p>
      You can add a new project using the web interface <%= link_to "here", new_project_path %>.
    </p>
    <p>
      Alternatively, to add a project using the command line, navigate to the directory where you unpacked this tool, and type:
    </p>
    <pre style="font-family: courier, serif">cruise add [project-name] -r [repository] -s [svn|git|hg|bzr]</pre>
    <p>
      If you have a problem with this command, you may find that
      <span style="font-family: courier, serif">cruise help</span> is ... helpful.
      If it isn't, there is always <%= link_to 'the manual', document_path('manual') %> and
      <a href="mailto:cruisecontrolrb-users@rubyforge.org">cruisecontrolrb-users@rubyforge.org</a> mailing list.
    </p>
  </div>
</div>

app/views/projects/_project.html.erb
<div id="project_<%= project.name %>" class="project build_<%= project.last_complete_build_status %>">
  <div class="upper">
    <div class="name">
      <%= link_to project.name, project_path(project), :id => project.name %>
    </div>

<!--
    TODO(mariozaizar) performance issues.
    <div class="commit-avatar">
      <%#= last_commit_avatar project -%>
    </div>
-->

    <div class="builder_control">
      <%= render :partial => "builds/build_buttons", :locals => { :project => project } %>
    </div>
  </div>

  <div class="lower">
    <div class="rss">
      <%= link_to image_tag('rss_light.gif'), :action => 'show', :id => project.name, :format => 'rss' %>
    </div>

    <% status = project.sleeping? ? project.last_complete_build_status : project.builder_state_and_activity %>

    <div class="project_status <%= status %>">
      <%= status.titleize %>
    </div>


    <!-- <% if 'success' == status %>
      <% coverage = project.last_successful_build_coverage %>
      <div class="coverage_status coverage_<%= coverage_status(coverage) %>">
        Cov <%= format_percent(coverage) %>
      </div>
    <% end %> -->

    <div class="status <%= project.last_complete_build_status %>">
      <%= project.last_complete_build_status.humanize %>
    </div>


    <div class="builder_status">
      <% if project.building? %>
        <%= link_to_build(project, project.last_build) %>
      <% elsif project.previously_built? %>
        <%= link_to_build_with_elapsed_time(project, project.last_complete_build) %>
      <% end %>
    </div>
  </div>

  <div class="clear"></div>
</div>

app/views/projects/_project_brief.html.erb
<tr id="project_<%= project.name %>" class="project build_<%= project.last_complete_build_status %>">
  <td class="project_name"><%= link_to project.name, :action => 'show', :id => project.name %></td>
  <td></td>
  <td></td>
  <td></td>
</tr>

app/views/projects/code.html.erb
<h1><%= File.join(params[:path]) %><span class="help">(latest version)</span></h1>

<div class="code">
<% line_number = 0 %>
<% @content.gsub("  ", " &nbsp;").split("\n").each do |line| %>
  <a name="<%= line_number += 1%>">
    <div class="line<%= @line == line_number ? ' selected_line' : ''%>">
      <span class="line_number"><%= line_number %>:</span><%= line.html_safe %>
    </div>
  </a>
<% end %>
</div>

app/views/projects/getting_started.html.erb
<div id="getting_started">
  <h1>Getting started with your new project</h1>

  <div class="main_content">
    <p>
      Now that you've created a project, you should use the CCRB API to configure your project. Projects are configured using a <code>cruise_config.rb</code> file that gets version-controlled and placed in the root of your project. A typical <code>cruise_config.rb</code> file looks like this:
    </P>

    <div class="terminal_output"><%= @config_example %></div>

    <p>To see the builds for your new project, go <%= link_to "here", project_path(@project) %>.</p>
  </div>
</div>

app/views/projects/index.html.erb
<% @rss_feeds = { 'All projects' => {:controller => 'projects', :action => 'index', :format => 'rss'} } -%>
<% @projects.each { |p| @rss_feeds["#{p.name} builds"] = project_url(p, :format => 'rss')} -%>

<div id="projects"
  data-refresh-path="<%= projects_path %>"
  data-refresh-interval="<%= CruiseControl::Configuration.dashboard_refresh_interval.to_i * 1000 %>">

  <% if @projects.empty? %>
    <%= render :partial => 'no_projects' %>
  <% else %>
    <%= render :partial => 'project', :collection => @projects %>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>Add a New Project</h1>

<div id="new_project">
  <%= form_for :project, :url => projects_path, :action => :post, :html => { :class => "new_project_form" } do |p| %>
    <dl class="name">
      <dt><%= p.label :name, "Name:" %></dt>
      <dd><%= p.text_field :name, :placeholder => "Name" %></dd>
    </dl>
  
    <dl class="scm">
      <%= p.fields_for :source_control do |scm| %>
      <dt><%= scm.label :repository, "Repository path:" %></dt>
      <dd><%= scm.text_field :repository, :placeholder => "Repository path" %></dd>
  
      <dt><%= scm.label :source_control, "Type of source control:" %></dt>
      <dd><%= scm.select :source_control, %w(Git Subversion Mercurial Bazaar) %></dd>

      <dt><%= scm.label :branch, "Repository branch:" %></dt>
      <dd><%= scm.text_field :branch, :placeholder => "Repository branch" %></dd>
      <% end %>

      <%= content_tag("button", "Create", :type => "submit") %></dt>
    </dl>
  <% end %>
</div>