config/routes.rb
CruiseControl::Application.routes.draw do
  match '/(.:format)' => 'projects#index', :as => :root
  match 'projects/code/:id/*path' => 'projects#code', :as => :code
  match 'projects/kill_all_builders' => 'projects#kill_all_builders'

  resources :projects do
    member do
      post :build, :constraints => { :id => /.*/ }
      post :release_note, :constraints => { :id => /.*/ }
      post :kill_build, :constraints => { :id => /.*/ }
      get :getting_started, :constraints => { :id => /.*/ }
    end
  end

  match 'builds/:project/latest_successful(/*path)' => 'builds#latest_successful', :as => :latest_successful_build, :project => /[^\/]+/
  match 'builds/:project/:build/artifacts/*path' => 'builds#artifact', :as => :build_artifact, :build => /[^\/]+/, :project => /[^\/]+/
  match 'builds/:project/:build' => 'builds#show', :as => :build, :build => /[^\/]+/, :project => /[^\/]+/
  match 'builds/:project' => 'builds#show', :as => :project_without_builds, :project => /[^\/]+/

  match 'documentation/plugins' => 'documentation#plugins', :as => :plugin_doc_list
  match 'documentation/plugins/:type/:name' => 'documentation#plugins', :as => :plugin_doc, :name => /[^\/]+/

  match 'documentation/*path' => 'documentation#get', :as => :document
  match 'documentation' => 'documentation#get', :as => :document_root

  match 'XmlStatusReport.aspx' => 'projects#index', :format => 'cctray'
  match 'XmlServerReport.aspx' => 'projects#index', :format => 'cctray'

  # TODO Remove this.
  match '/:controller(/:action(/:id))'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="version">
    <div>Version <%= CruiseControl::VERSION::STRING %></div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <ul class="main_menu">
    <li class="menu_item">
      <%= link_to 'All Projects', projects_path, :class => ( current_page?(root_path) || current_page?(projects_path) ) ? 'current' : '' %>
    </li>
    
    <% unless CruiseControl::Configuration.disable_admin_ui || CruiseControl::Configuration.disable_add_project %>
      <li class="menu_item">
        <%= link_to 'Add Project', new_project_path, :class => current_page?(new_project_path) ? 'current' : '' %>
      </li>
    <% end %>

    <% if current_page?(:controller => "builds", :action => "show") %>
      <li class="menu_item">
        <%= link_to @project.name, project_path(@project), :class => 'current' %>
      </li>
    <% end %>

    <li class="menu_item">
      <%= link_to 'Help', document_root_path %>
    </li>
  </ul>

  <div class="cc_logo">
    <%= link_to image_tag("cruise_logo.png"), root_path %>
  </div>

  <% unless flash[:notice].blank? -%>
    <div class="flash_notice"><%= h flash[:notice] %></div>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>CruiseControl.rb<%= @title ? " - " + @title : '' %></title>
  <%= tag :link, :rel => "stylesheet/less", :type => "text/css", :href => path_to_stylesheet('cruisecontrol.less') %>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/cupertino/jquery-ui.css" />
  <%= stylesheet_link_tag 'site', :media => 'all' if Rails.root.join("public", "stylesheets", "site.css").exist? %>

  <% if @autorefresh %>
    <meta http-equiv="refresh" content="<%= CruiseControl::Configuration.dashboard_refresh_interval.to_i %>">
    <meta http-equiv="cache-control" content="no-cache">
  <% end %>
  <% if @rss_feeds -%>
    <% @rss_feeds.sort.each do |title, url| -%>
      <%= auto_discovery_link_tag :rss, url_path(url), {:title => title} %>
    <% end -%>
  <% end -%>
  <%= javascript_include_tag "jquery-1.6.1" %>
  <%= javascript_include_tag "jquery-ui/js/jquery-ui-1.8.21.custom.min" %>
  <%= javascript_include_tag "less-1.1.0" %>
  <%= javascript_include_tag "application" %>
</head>

<body>

  <%= render :partial => '/layouts/header' %>

  <div id="content">
    <%= yield %>

    <% if Project.all.any? -%>
      <%= form_for :project, :url => projects_kill_all_builders_path, :action => :post do |p| %>
        <button type="submit" name="kill_all" class="kill_all_build_button">Kill all Builders</button>
      <% end -%>
    <% end -%>
  </div>
  <%= render :partial => '/layouts/footer' %>
  
  <style>
    .builder_status>a.success, li.build_link a.success, #build .left_column .builds_list .build_link.selected a.success {
        background-color: #3f3;
    }

    li.build_link a.failed, #build .left_column .builds_list .build_link.selected a.failed {
        background-color: #f33;
    }
  </style>

</body>
</html>

app/views/layouts/documentation.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>CruiseControl.rb<%= @title ? " - " + @title : '' %></title>
  <meta name="description" content="Lightweight continuous integration tool" />
  <meta name="keywords"
        content="continuous integration, cruisecontrol, ruby, rails, build, deployment, software, development, agile" />
  <%= stylesheet_link_tag '/thoughtworks_studios/reset', :media => 'all' %>
  <%= stylesheet_link_tag '/thoughtworks_studios/fonts', :media => 'all' %>
  <%= stylesheet_link_tag '/thoughtworks_studios/grids', :media => 'all' %>
  <%= stylesheet_link_tag '/thoughtworks_studios/base', :media => 'all' %>
  <%= stylesheet_link_tag 'documentation', :media => 'all' %>
  <%= javascript_include_tag '/thoughtworks_studios/page' %>
  <%= javascript_include_tag :all %>
</head>
<body>
	<div id="doc" class="yui-t4">
    <%= render :partial => '/documentation/header' %>

		<div id="bd" class="thick">
		  <div class="yui-b" id="side-bar">
		    <div class="inner">
          <%= raw render :partial => '/documentation/' + (@sidebar || 'sidebar_docs') %>
		    </div>
      </div>

		  <div id="yui-main">
		    <div class="yui-b">
		      <div class="inner">
		        <%= yield %>
		      </div>
		    </div>
		  </div>
    </div>

    <%= render :partial => '/documentation/footer' %>
  </div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-9566218-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>